import type {
  AdminValidationItem,
  AmpasListing,
  AromaMatchQuestion,
  AromaMatchRecommendation,
  Bundle,
  CartItem,
  Money,
  NilamPassport,
  OrderSummary,
  Product,
  ProductCategory,
  Review,
  Seller,
  Promo,
} from "@/lib/contracts";

const idr = (amount: number): Money => ({
  amount,
  currency: "IDR",
});

export const sellers: Seller[] = [
  {
    id: "seller-aceh-aroma",
    slug: "aceh-aroma-house",
    displayName: "Aceh Aroma House",
    type: "umkm",
    location: {
      province: "Aceh",
      city: "Aceh Selatan",
      district: "Tapaktuan",
    },
    verificationStatus: "verified",
    joinedAt: "2026-01-12T09:00:00.000Z",
    ratingAverage: 4.9,
    totalReviews: 128,
    contactChannel: "WhatsApp Business",
  },
  {
    id: "seller-nilam-lestari",
    slug: "nilam-lestari-coop",
    displayName: "Koperasi Nilam Lestari",
    type: "cooperative",
    location: {
      province: "Aceh",
      city: "Aceh Jaya",
      district: "Panga",
    },
    verificationStatus: "verified",
    joinedAt: "2026-02-04T08:30:00.000Z",
    ratingAverage: 4.8,
    totalReviews: 86,
    contactChannel: "Marketplace chat",
  },
  {
    id: "seller-gayo-distill",
    slug: "gayo-distill-lab",
    displayName: "Gayo Distill Lab",
    type: "distiller",
    location: {
      province: "Aceh",
      city: "Gayo Lues",
      district: "Blangkejeren",
    },
    verificationStatus: "verified",
    joinedAt: "2026-02-20T10:15:00.000Z",
    ratingAverage: 4.7,
    totalReviews: 42,
    contactChannel: "WhatsApp Business",
  },
];

export const productCategories: ProductCategory[] = [
  {
    id: "category-aromatherapy",
    slug: "aromaterapi",
    name: "Aromaterapi",
    description: "Roll-on, essential oil, dan diffuser berbasis nilam Aceh.",
    targetMarket: "b2c",
    image: {
      src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
      alt: "Botol essential oil amber di atas dudukan kayu.",
    },
  },
  {
    id: "category-body-care",
    slug: "body-care",
    name: "Body Care",
    description: "Sabun, body oil, dan perawatan natural dengan profil nilam.",
    targetMarket: "b2c",
    image: {
      src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
      alt: "Produk sabun natural di studio cerah.",
    },
  },
  {
    id: "category-home-fragrance",
    slug: "home-fragrance",
    name: "Home Fragrance",
    description: "Diffuser blend dan parfum ruangan dengan aroma woody.",
    targetMarket: "b2c",
    image: {
      src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
      alt: "Botol parfum dan diffuser di meja elegan.",
    },
  },
];

export const products: Product[] = [
  {
    id: "product-roll-on-relief",
    slug: "roll-on-nilam-relief",
    sellerId: "seller-aceh-aroma",
    categoryId: "category-aromatherapy",
    passportId: "passport-roll-on-relief",
    name: "Roll-on Nilam Relief",
    shortDescription: "Roll-on titik nadi untuk rutinitas relaksasi harian.",
    form: "roll-on",
    functions: ["relaxation", "sleep-support"],
    tags: ["best-seller", "nilam-passport"],
    price: idr(89000),
    originalPrice: idr(109000),
    stock: 42,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
      alt: "Produk kosmetik natural dengan kuas dan botol kecil.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
        alt: "Flatlay produk roll-on dan kosmetik natural.",
      },
    ],
    featuredRank: 1,
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-06-20T11:00:00.000Z",
  },
  {
    id: "product-essential-oil-aceh",
    slug: "essential-oil-aceh",
    sellerId: "seller-nilam-lestari",
    categoryId: "category-aromatherapy",
    passportId: "passport-essential-oil-aceh",
    name: "Essential Oil Aceh",
    shortDescription: "Minyak atsiri nilam Aceh untuk diffuser dan blend.",
    form: "essential-oil",
    functions: ["relaxation", "home-fragrance"],
    tags: ["nilam-passport", "limited-batch"],
    price: idr(145000),
    originalPrice: idr(175000),
    stock: 26,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
      alt: "Botol essential oil amber di atas dudukan kayu.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
        alt: "Botol essential oil dengan bayangan daun.",
      },
    ],
    featuredRank: 2,
    createdAt: "2026-03-09T09:00:00.000Z",
    updatedAt: "2026-06-19T11:00:00.000Z",
  },
  {
    id: "product-artisan-soap",
    slug: "sabun-nilam-artisan",
    sellerId: "seller-aceh-aroma",
    categoryId: "category-body-care",
    passportId: "passport-artisan-soap",
    name: "Sabun Nilam Artisan",
    shortDescription: "Sabun natural batch kecil dengan aroma earthy lembut.",
    form: "soap",
    functions: ["skin-care", "gift"],
    tags: ["new-arrival"],
    price: idr(42000),
    originalPrice: idr(55000),
    stock: 64,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
      alt: "Produk sabun natural di studio cerah.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
        alt: "Sabun natural dengan kemasan bersih.",
      },
    ],
    featuredRank: 3,
    createdAt: "2026-04-02T09:00:00.000Z",
    updatedAt: "2026-06-18T11:00:00.000Z",
  },
  {
    id: "product-diffuser-blend",
    slug: "diffuser-blend-patchouli",
    sellerId: "seller-gayo-distill",
    categoryId: "category-home-fragrance",
    passportId: "passport-diffuser-blend",
    name: "Diffuser Blend Patchouli",
    shortDescription: "Blend diffuser patchouli untuk suasana ruang yang tenang.",
    form: "diffuser",
    functions: ["home-fragrance", "focus"],
    tags: ["aroma-calm"],
    price: idr(128000),
    originalPrice: idr(149000),
    stock: 31,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
      alt: "Botol parfum dan aroma diffuser di meja elegan.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
        alt: "Botol diffuser premium di studio.",
      },
    ],
    featuredRank: 4,
    createdAt: "2026-04-12T09:00:00.000Z",
    updatedAt: "2026-06-17T11:00:00.000Z",
  },
  {
    id: "product-body-oil-lux",
    slug: "body-oil-luxury",
    sellerId: "seller-aceh-aroma",
    categoryId: "category-body-care",
    passportId: "passport-body-oil-lux",
    name: "Body Oil Luxury",
    shortDescription: "Body oil premium dengan kandungan minyak nilam murni untuk hidrasi kulit.",
    form: "body-oil",
    functions: ["skin-care", "relaxation"],
    tags: ["new-arrival", "nilam-passport"],
    price: idr(175000),
    originalPrice: idr(199000),
    stock: 18,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
      alt: "Botol body oil premium amber.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
        alt: "Detail botol body oil premium.",
      },
    ],
    featuredRank: 5,
    createdAt: "2026-05-01T10:00:00.000Z",
    updatedAt: "2026-06-21T09:00:00.000Z",
  },
  {
    id: "product-candles-set",
    slug: "lilin-aromaterapi-nilam",
    sellerId: "seller-gayo-distill",
    categoryId: "category-aromatherapy",
    passportId: "passport-candles-set",
    name: "Lilin Aromaterapi Nilam",
    shortDescription: "Lilin aromaterapi nilam & lavender untuk membantu kualitas tidur.",
    form: "essential-oil",
    functions: ["relaxation", "sleep-support"],
    tags: ["new-arrival"],
    price: idr(95000),
    originalPrice: idr(115000),
    stock: 22,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
      alt: "Lilin aromaterapi menyala.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
        alt: "Lilin aromaterapi.",
      },
    ],
    featuredRank: 6,
    createdAt: "2026-05-15T09:00:00.000Z",
    updatedAt: "2026-06-22T10:00:00.000Z",
  },
  {
    id: "product-perfume-local",
    slug: "parfum-nilam-local",
    sellerId: "seller-aceh-aroma",
    categoryId: "category-aromatherapy",
    passportId: "passport-perfume-local",
    name: "Parfum Nilam Lokal",
    shortDescription: "Parfum eau de toilette dengan base note nilam Aceh autentik.",
    form: "perfume",
    functions: ["gift", "relaxation"],
    tags: ["best-seller", "nilam-passport"],
    price: idr(210000),
    originalPrice: idr(250000),
    stock: 15,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
      alt: "Botol parfum nilam lokal premium.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
        alt: "Detail botol parfum nilam.",
      },
    ],
    featuredRank: 7,
    createdAt: "2026-05-20T09:00:00.000Z",
    updatedAt: "2026-06-23T10:00:00.000Z",
  },
  {
    id: "product-roll-on-focus",
    slug: "roll-on-nilam-focus",
    sellerId: "seller-gayo-distill",
    categoryId: "category-aromatherapy",
    passportId: "passport-roll-on-focus",
    name: "Roll-on Nilam Focus",
    shortDescription: "Roll-on aromaterapi untuk meningkatkan konsentrasi saat bekerja.",
    form: "roll-on",
    functions: ["focus", "relaxation"],
    tags: ["new-arrival"],
    price: idr(79000),
    originalPrice: idr(99000),
    stock: 35,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
      alt: "Roll-on aromaterapi untuk fokus.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
        alt: "Detail roll-on aromaterapi.",
      },
    ],
    featuredRank: 8,
    createdAt: "2026-05-22T09:00:00.000Z",
    updatedAt: "2026-06-24T10:00:00.000Z",
  },
  {
    id: "product-soap-gift-set",
    slug: "sabun-nilam-gift-set",
    sellerId: "seller-nilam-lestari",
    categoryId: "category-body-care",
    passportId: "passport-soap-gift-set",
    name: "Sabun Nilam Gift Set",
    shortDescription: "Set tiga sabun artisan nilam dalam kemasan hadiah premium.",
    form: "soap",
    functions: ["skin-care", "gift"],
    tags: ["best-seller"],
    price: idr(120000),
    originalPrice: idr(140000),
    stock: 28,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
      alt: "Set sabun nilam dalam kemasan hadiah.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
        alt: "Detail sabun nilam gift set.",
      },
    ],
    featuredRank: 9,
    createdAt: "2026-05-25T09:00:00.000Z",
    updatedAt: "2026-06-25T10:00:00.000Z",
  },
  {
    id: "product-lotion-nilam",
    slug: "losion-nilam-hydrate",
    sellerId: "seller-aceh-aroma",
    categoryId: "category-body-care",
    passportId: "passport-lotion-nilam",
    name: "Losion Nilam Hydrate",
    shortDescription: "Losion pelembap ringan dengan ekstrak nilam untuk kulit kering.",
    form: "body-oil",
    functions: ["skin-care"],
    tags: ["nilam-passport"],
    price: idr(68000),
    originalPrice: idr(85000),
    stock: 50,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
      alt: "Botol losion nilam untuk hidrasi kulit.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
        alt: "Detail losion nilam.",
      },
    ],
    featuredRank: 10,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-06-26T10:00:00.000Z",
  },
  {
    id: "product-reed-diffuser",
    slug: "reed-diffuser-patchouli",
    sellerId: "seller-gayo-distill",
    categoryId: "category-home-fragrance",
    passportId: "passport-reed-diffuser",
    name: "Reed Diffuser Patchouli",
    shortDescription: "Reed diffuser elegan dengan aroma patchouli untuk ruang tamu dan kamar.",
    form: "diffuser",
    functions: ["home-fragrance", "relaxation"],
    tags: ["new-arrival", "aroma-calm"],
    price: idr(155000),
    originalPrice: idr(185000),
    stock: 12,
    status: "published",
    image: {
      src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
      alt: "Reed diffuser patchouli di meja.",
    },
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
        alt: "Detail reed diffuser patchouli.",
      },
    ],
    featuredRank: 11,
    createdAt: "2026-06-05T09:00:00.000Z",
    updatedAt: "2026-06-27T10:00:00.000Z",
  },
];

export const nilamPassports: NilamPassport[] = [
  {
    id: "passport-body-oil-lux",
    productId: "product-body-oil-lux",
    origin: "Gayo Lues",
    productKind: "body-oil",
    aromaProfile: ["warm woody", "sweet", "calming"],
    functions: ["skin-care", "relaxation"],
    usage: "Oleskan secukupnya pada area tubuh setelah mandi.",
    safetyNotes: "Hanya untuk pemakaian luar.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-21T09:00:00.000Z",
  },
  {
    id: "passport-roll-on-relief",
    productId: "product-roll-on-relief",
    origin: "Aceh Selatan",
    productKind: "roll-on",
    aromaProfile: ["woody", "earthy", "calming"],
    functions: ["relaxation", "sleep-support"],
    usage: "Roll-on tipis pada titik nadi, maksimal tiga kali sehari.",
    safetyNotes: "Patch test disarankan untuk kulit sensitif.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-21T08:00:00.000Z",
  },
  {
    id: "passport-essential-oil-aceh",
    productId: "product-essential-oil-aceh",
    origin: "Aceh Jaya",
    productKind: "essential-oil",
    aromaProfile: ["deep woody", "smoky", "green"],
    functions: ["relaxation", "home-fragrance"],
    usage: "Gunakan dua sampai tiga tetes pada diffuser berisi air.",
    safetyNotes: "Tidak untuk ditelan dan jauhkan dari anak-anak.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-21T08:05:00.000Z",
  },
  {
    id: "passport-artisan-soap",
    productId: "product-artisan-soap",
    origin: "Aceh Selatan",
    productKind: "soap",
    aromaProfile: ["soft earthy", "herbal"],
    functions: ["skin-care", "gift"],
    usage: "Basahi, busakan, lalu bilas sampai bersih.",
    safetyNotes: "Hentikan pemakaian jika terjadi iritasi.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-21T08:10:00.000Z",
  },
  {
    id: "passport-diffuser-blend",
    productId: "product-diffuser-blend",
    origin: "Gayo Lues",
    productKind: "diffuser",
    aromaProfile: ["woody", "amber", "calming"],
    functions: ["home-fragrance", "focus"],
    usage: "Tuang pada diffuser reed atau electric diffuser sesuai petunjuk alat.",
    safetyNotes: "Jauhkan dari sumber api dan permukaan mudah rusak.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-21T08:15:00.000Z",
  },
  {
    id: "passport-candles-set",
    productId: "product-candles-set",
    origin: "Gayo Lues",
    productKind: "essential-oil",
    aromaProfile: ["woody", "lavender", "calming"],
    functions: ["relaxation", "sleep-support"],
    usage: "Nyalakan di ruangan berventilasi baik, jauhkan dari benda mudah terbakar.",
    safetyNotes: "Jangan tinggalkan lilin menyala tanpa pengawasan.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-22T08:00:00.000Z",
  },
  {
    id: "passport-perfume-local",
    productId: "product-perfume-local",
    origin: "Aceh Selatan",
    productKind: "perfume",
    aromaProfile: ["patchouli", "musk", "amber"],
    functions: ["gift", "relaxation"],
    usage: "Semprotkan pada titik nadi seperti pergelangan tangan dan leher.",
    safetyNotes: "Hanya untuk pemakaian luar. Hindari kontak dengan mata.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-23T08:00:00.000Z",
  },
  {
    id: "passport-roll-on-focus",
    productId: "product-roll-on-focus",
    origin: "Gayo Lues",
    productKind: "roll-on",
    aromaProfile: ["minty woody", "fresh", "green"],
    functions: ["focus", "relaxation"],
    usage: "Roll-on pada pelipis atau pergelangan tangan saat butuh fokus.",
    safetyNotes: "Patch test disarankan untuk kulit sensitif.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-24T08:00:00.000Z",
  },
  {
    id: "passport-soap-gift-set",
    productId: "product-soap-gift-set",
    origin: "Aceh Jaya",
    productKind: "soap",
    aromaProfile: ["floral earthy", "herbal", "soft"],
    functions: ["skin-care", "gift"],
    usage: "Basahi, busakan, dan bilas. Cocok untuk semua jenis kulit.",
    safetyNotes: "Hentikan pemakaian jika terjadi iritasi kulit.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-25T08:00:00.000Z",
  },
  {
    id: "passport-lotion-nilam",
    productId: "product-lotion-nilam",
    origin: "Aceh Selatan",
    productKind: "body-oil",
    aromaProfile: ["soft woody", "creamy"],
    functions: ["skin-care"],
    usage: "Oleskan pada kulit setelah mandi untuk hasil terbaik.",
    safetyNotes: "Hanya untuk pemakaian luar.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-26T08:00:00.000Z",
  },
  {
    id: "passport-reed-diffuser",
    productId: "product-reed-diffuser",
    origin: "Gayo Lues",
    productKind: "diffuser",
    aromaProfile: ["deep patchouli", "woody", "warm"],
    functions: ["home-fragrance", "relaxation"],
    usage: "Tempatkan di meja, balik reed stick setiap minggu untuk menjaga aroma.",
    safetyNotes: "Jauhkan dari jangkauan anak-anak dan sumber api.",
    validationStatus: "validated",
    validatedBy: "admin-niloka-curation",
    validatedAt: "2026-06-27T08:00:00.000Z",
  },
];

export const ampasListings: AmpasListing[] = [
  {
    id: "ampas-gayo-dry-biomass",
    slug: "ampas-nilam-kering-gayo",
    sellerId: "seller-gayo-distill",
    condition: "dry",
    quantityKg: 850,
    pricePerKg: idr(1800),
    location: {
      province: "Aceh",
      city: "Gayo Lues",
      district: "Blangkejeren",
    },
    distillationProcess: "Penyulingan uap batch kecil, dikeringanginkan 48 jam.",
    usageTags: ["compost", "briquette", "mulch", "industrial-cellulose"],
    status: "active",
    image: {
      src: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80",
      alt: "Bahan alami dan minyak nilam sebagai bagian ekonomi sirkular.",
    },
    disclaimer:
      "Tag penggunaan adalah klaim seller; NILOKA tidak memverifikasi kandungan atau kualitas ampas.",
    createdAt: "2026-05-10T09:00:00.000Z",
    updatedAt: "2026-06-22T09:00:00.000Z",
    wholesaleEnabled: true,
    wholesaleMinQtyKg: 25,
    wholesalePricePerKg: idr(1500),
  },
  {
    id: "ampas-panga-wet-compost",
    slug: "ampas-nilam-basah-panga",
    sellerId: "seller-nilam-lestari",
    condition: "wet",
    quantityKg: 420,
    pricePerKg: idr(900),
    location: {
      province: "Aceh",
      city: "Aceh Jaya",
      district: "Panga",
    },
    distillationProcess: "Sisa penyulingan harian, belum dikeringkan.",
    usageTags: ["compost", "mushroom-media", "animal-feed"],
    status: "active",
    image: {
      src: "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=80",
      alt: "Produk natural dan bahan produksi tersusun rapi.",
    },
    disclaimer:
      "Tag penggunaan adalah klaim seller; NILOKA tidak memverifikasi kandungan atau kualitas ampas.",
    createdAt: "2026-05-13T09:00:00.000Z",
    updatedAt: "2026-06-22T09:30:00.000Z",
    wholesaleEnabled: false,
  },
];

export const reviews: Review[] = [
  {
    id: "review-roll-on-001",
    productId: "product-roll-on-relief",
    sellerId: "seller-aceh-aroma",
    authorName: "Maya Putri",
    rating: 5,
    tags: [],
    body: "Aromanya earthy dan tidak menusuk, informasi passport juga jelas.",
    createdAt: "2026-06-11T10:00:00.000Z",
  },
  {
    id: "review-essential-oil-001",
    productId: "product-essential-oil-aceh",
    sellerId: "seller-nilam-lestari",
    authorName: "Raka Pratama",
    rating: 5,
    tags: [],
    body: "Blend diffuser jadi lebih hangat dan tahan lama.",
    createdAt: "2026-06-13T10:00:00.000Z",
  },
  {
    id: "review-artisan-soap-001",
    productId: "product-artisan-soap",
    sellerId: "seller-aceh-aroma",
    authorName: "Faisal Ahmad",
    rating: 4,
    tags: [],
    body: "Sabun nilam artisan ini lembut sekali di kulit sensitif. Wanginya sangat natural.",
    createdAt: "2026-06-15T08:30:00.000Z",
  },
  {
    id: "review-diffuser-blend-001",
    productId: "product-diffuser-blend",
    sellerId: "seller-gayo-distill",
    authorName: "Nadia Lestari",
    rating: 5,
    tags: [],
    body: "Aromanya menenangkan sekali untuk kerja di rumah. Pelayanan cepat!",
    createdAt: "2026-06-20T14:20:00.000Z",
  },
  {
    id: "review-essential-oil-002",
    productId: "product-essential-oil-aceh",
    sellerId: "seller-nilam-lestari",
    authorName: "Hendra Wijaya",
    rating: 5,
    tags: [],
    body: "Kualitas minyak nilam terbaik dari Panga. Keterangan asal bahan di passport sangat membantu.",
    createdAt: "2026-06-22T11:45:00.000Z",
  },
  {
    id: "review-artisan-soap-002",
    productId: "product-artisan-soap",
    sellerId: "seller-aceh-aroma",
    authorName: "Cut Aura",
    rating: 5,
    tags: [],
    body: "Wangi minyak nilamnya benar-benar menenangkan. Kulit saya jadi terasa lebih lembap setelah mandi.",
    createdAt: "2026-06-25T09:15:00.000Z",
  },
];

export const promos: Promo[] = [
  {
    id: "promo-aroma-week",
    sellerId: "seller-aceh-aroma",
    title: "Aroma Week 10%",
    code: "ATSIRI10",
    status: "active",
    type: "percentage",
    value: 10,
    startsAt: "2026-07-01T00:00:00.000Z",
    endsAt: "2026-07-15T23:59:59.000Z",
    minSubtotal: idr(50000),
    usageLimit: 250,
    usedCount: 64,
    productIds: ["product-roll-on-relief", "product-artisan-soap"],
  },
  {
    id: "promo-coop-15k",
    sellerId: "seller-nilam-lestari",
    title: "Potongan Koperasi Rp15.000",
    code: "COOP15K",
    status: "active",
    type: "fixed-amount",
    value: 15000,
    startsAt: "2026-07-01T00:00:00.000Z",
    endsAt: "2026-07-20T23:59:59.000Z",
    minSubtotal: idr(120000),
    usageLimit: 100,
    usedCount: 21,
    productIds: ["product-essential-oil-aceh"],
  },
  {
    id: "promo-niloka-free",
    sellerId: "seller-aceh-aroma",
    title: "Gratis Ongkir Produk Body Care",
    code: "NILAMFREE",
    status: "active",
    type: "free-shipping",
    value: 0,
    startsAt: "2026-07-04T00:00:00.000Z",
    endsAt: "2026-07-30T23:59:59.000Z",
    minSubtotal: idr(150000),
    usageLimit: 80,
    usedCount: 12,
    productIds: ["product-body-oil-lux", "product-artisan-soap"],
  },
  {
    id: "promo-future-bundle",
    sellerId: "seller-gayo-distill",
    title: "Bundling Home Fragrance 12%",
    code: "GAYO12",
    status: "scheduled",
    type: "percentage",
    value: 12,
    startsAt: "2026-08-01T00:00:00.000Z",
    endsAt: "2026-08-15T23:59:59.000Z",
    minSubtotal: idr(200000),
    usageLimit: 120,
    usedCount: 0,
    productIds: ["product-diffuser-blend"],
  },
];

export const bundles: Bundle[] = [
  {
    id: "bundle-calm-home",
    slug: "calm-home-starter",
    title: "Calm Home Starter",
    type: "cross-seller",
    productIds: ["product-essential-oil-aceh", "product-diffuser-blend"],
    price: idr(249000),
    description: "Paket diffuser dan essential oil untuk ruang kerja tenang.",
  },
];

export const cartItems: CartItem[] = [
  {
    id: "cart-item-roll-on",
    kind: "product",
    productId: "product-roll-on-relief",
    ampasListingId: null,
    quantity: 1,
    unitPrice: idr(89000),
  },
  {
    id: "cart-item-ampas-gayo",
    kind: "ampas-listing",
    productId: null,
    ampasListingId: "ampas-gayo-dry-biomass",
    quantity: 100,
    unitPrice: idr(1800),
  },
];

export const orderSummaries: OrderSummary[] = [
  {
    id: "order-preview-001",
    status: "draft",
    items: cartItems,
    subtotal: idr(269000),
    platformFee: idr(9400),
    shippingEstimate: idr(28000),
    grandTotal: idr(306400),
  },
];

export const aromaMatchQuestions: AromaMatchQuestion[] = [
  {
    id: "aroma-purpose",
    step: 1,
    prompt: "Apa tujuan utama penggunaan produk nilam Anda?",
    kind: "single-choice",
    options: [
      {
        id: "purpose-relax",
        label: "Relaksasi & Tidur Nyenyak",
        productFunctions: ["relaxation", "sleep-support"],
      },
      {
        id: "purpose-focus",
        label: "Fokus & Peningkatan Energi",
        productFunctions: ["focus"],
      },
      {
        id: "purpose-room",
        label: "Penyegar & Keharuman Ruangan",
        productFunctions: ["home-fragrance"],
      },
      {
        id: "purpose-skin",
        label: "Perawatan Kulit & Tubuh",
        productFunctions: ["skin-care"],
      },
      {
        id: "purpose-gift",
        label: "Hadiah / Bingkisan Spesial",
        productFunctions: ["gift"],
      },
    ],
  },
  {
    id: "aroma-profile",
    step: 2,
    prompt: "Profil aroma wewangian apa yang paling Anda sukai?",
    kind: "multi-choice",
    options: [
      {
        id: "aroma-woody",
        label: "Woody (Kayu-kayuan hangat, menenangkan & bersahaja)",
        productFunctions: [],
      },
      {
        id: "aroma-citrus",
        label: "Citrus (Segar jeruk, membangkitkan semangat & ceria)",
        productFunctions: [],
      },
      {
        id: "aroma-herbal",
        label: "Herbal & Rempah (Dedaunan alami, segar & berenergi)",
        productFunctions: [],
      },
      {
        id: "aroma-floral",
        label: "Floral & Sweet (Manis bunga, elegan & romantis)",
        productFunctions: [],
      },
    ],
  },
  {
    id: "aroma-form",
    step: 3,
    prompt: "Bentuk produk nilam apa yang paling praktis bagi Anda?",
    kind: "single-choice",
    options: [
      {
        id: "form-oil",
        label: "Essential Oil Murni (Konsentrat tinggi untuk diffuser/campuran)",
        productFunctions: [],
      },
      {
        id: "form-rollon",
        label: "Roll-on Aromaterapi (Praktis dioles di kulit kapan saja)",
        productFunctions: [],
      },
      {
        id: "form-soap",
        label: "Sabun Artisan & Losion (Untuk mandi dan kelembaban kulit)",
        productFunctions: [],
      },
      {
        id: "form-diffuser",
        label: "Reed Diffuser & Lilin (Penyebar wangi ruangan otomatis)",
        productFunctions: [],
      },
    ],
  },
  {
    id: "aroma-budget",
    step: 4,
    prompt: "Berapa anggaran (budget) yang Anda rencanakan?",
    kind: "budget-range",
    options: [
      {
        id: "budget-low",
        label: "Di bawah Rp 75.000 (Ekonomis)",
        productFunctions: [],
      },
      {
        id: "budget-medium",
        label: "Rp 75.000 - Rp 150.000 (Standar)",
        productFunctions: [],
      },
      {
        id: "budget-high",
        label: "Di atas Rp 150.000 (Premium/Gift Set)",
        productFunctions: [],
      },
    ],
  },
];

export const aromaMatchRecommendations: AromaMatchRecommendation[] = [
  {
    id: "recommend-roll-on-relief",
    productId: "product-roll-on-relief",
    score: 96,
    reason: "Cocok untuk pengguna yang mencari relaksasi ringan dan format praktis.",
    matchedTags: ["best-seller", "nilam-passport"],
  },
  {
    id: "recommend-diffuser-blend",
    productId: "product-diffuser-blend",
    score: 88,
    reason: "Aroma calm dan fungsi home fragrance cocok untuk ruang kerja.",
    matchedTags: ["aroma-calm"],
  },
];

export const adminValidationItems: AdminValidationItem[] = [
  {
    id: "validation-passport-roll-on",
    target: "nilam-passport",
    targetId: "passport-roll-on-relief",
    status: "approved",
    submittedBy: "seller-aceh-aroma",
    submittedAt: "2026-06-20T08:00:00.000Z",
    notes: "Data asal bahan, profil aroma, dan safety notes lengkap.",
  },
  {
    id: "validation-seller-gayo",
    target: "seller",
    targetId: "seller-gayo-distill",
    status: "approved",
    submittedBy: "seller-gayo-distill",
    submittedAt: "2026-06-18T08:00:00.000Z",
    notes: "Seller distiller aktif dengan dokumen onboarding lengkap.",
  },
  {
    id: "validation-seller-nilam-lestari",
    target: "seller",
    targetId: "seller-nilam-lestari",
    status: "queued",
    submittedBy: "seller-nilam-lestari",
    submittedAt: "2026-07-02T10:15:00.000Z",
    notes: "Koperasi baru mendaftar. Menunggu verifikasi dokumen legalitas.",
  },
  {
    id: "validation-product-sabun-artisan",
    target: "product",
    targetId: "product-sabun-nilam-artisan",
    status: "queued",
    submittedBy: "seller-aceh-aroma",
    submittedAt: "2026-07-01T14:30:00.000Z",
    notes: "Produk baru dari seller terverifikasi. Perlu review klaim bahan alami.",
  },
  {
    id: "validation-passport-essential-oil",
    target: "nilam-passport",
    targetId: "passport-essential-oil-aceh",
    status: "approved",
    submittedBy: "seller-aceh-aroma",
    submittedAt: "2026-05-15T09:00:00.000Z",
    notes: "Kadar PA 34.2% sesuai hasil uji lab independen. Disetujui.",
  },
  {
    id: "validation-product-diffuser-gayo",
    target: "product",
    targetId: "product-diffuser-gayo",
    status: "approved",
    submittedBy: "seller-gayo-distill",
    submittedAt: "2026-06-10T11:00:00.000Z",
    notes: "Deskripsi produk jelas dan akurat. Listing disetujui.",
  },
  {
    id: "validation-passport-sabun-draft",
    target: "nilam-passport",
    targetId: "passport-sabun-nilam-artisan",
    status: "queued",
    submittedBy: "seller-aceh-aroma",
    submittedAt: "2026-07-03T16:45:00.000Z",
    notes: "Draf paspor baru diajukan. Belum ada lampiran hasil uji PA.",
  },
  {
    id: "validation-seller-aceh-aroma",
    target: "seller",
    targetId: "seller-aceh-aroma",
    status: "approved",
    submittedBy: "seller-aceh-aroma",
    submittedAt: "2026-01-15T08:00:00.000Z",
    notes: "UMKM aktif sejak Januari 2026. Semua dokumen lengkap.",
  },
  {
    id: "validation-product-body-oil",
    target: "product",
    targetId: "product-body-oil-nilam",
    status: "rejected",
    submittedBy: "seller-nilam-lestari",
    submittedAt: "2026-06-28T13:20:00.000Z",
    notes: "Ditolak: klaim 'menyembuhkan penyakit kulit' melanggar regulasi BPOM. Perlu revisi deskripsi.",
  },
];
